##' @export
##'
##' @rdname px_file_types
file_types <- function()
    readRDS(dir(system.file("extdata", package = "rpx"),
                pattern = "file_types.rds",
                full.names = TRUE))

##' @title Infer file type
##'
##' @description
##'
##' The `px_file_types()` function inferres mass spectrometry and
##' proteomics file types based on a currated table of file types and
##' associated patterns. This table can be accessed with
##' `file_types()`. See the examples below for the content of the
##' tables.
##'
##' The file types table is generated by `scripts/make_file_types.R`.
##'
##' @param fls `character()` of file names whose types need to be
##'     inferred based on their file extenstion.
##'
##' @param types `data.frame` of file types. Default is
##'     `file_types()`.
##'
##' @return A `data.frame` with the filenames and their inferred
##'     types.
##'
##' @export
##'
##' @author Laurent Gatto with contributions from Dr. Samuel Wein to
##'     identify several file types.
##'
##' @examples
##'
##' file_types()
##'
##' px_file_types("foo")
##' px_file_types("foo.mzML")
##' px_file_types("foo.raw")
##' px_file_types("foo.txt")
##' px_file_types("foo.R")
##' px_file_types("foo.fasta")
##'
##' px_file_types(c("foo", "foo.mzML", "foo.R", "foo.fasta"))
px_file_types <- function(fls, types = file_types()) {
    ans <- data.frame(file = fls, type = NA_character_)
    for (.ext in 1:nrow(types)) {
        i <- grep(types$pattern[.ext], fls, perl = TRUE)
        ans$type[i] <- types$type[.ext]
    }
    ans
}
